server:
  port: ${API_GATEWAY_PORT:8765}
spring:
  application:
    name: ${APPLICATION_GATEWAY:api-gateway}
  cloud:
    gateway:
      routes:
        - id: booking-route
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
          filters:
            - name: CircuitBreaker
              args:
                name: booking-route
                fallbackUri: forward:/booking-fallback

eureka:
  client:
    register-with-eureka: ${REGISTER_GATEWAY_WITH_EUREKA:true}
    service-url:
      defaultZone: ${eureka_client_serviceUrl_defaultZone:http://localhost:8761/eureka/}
    fetch-registry: ${eureka_client_fetch_registry:true}