server:
  port: ${server_port:8081}
spring:
  application:
    name: ${APPLICATION_NAME:booking-service}
eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTRATION:true}
    service-url:
      defaultZone: ${eureka_client_serviceUrl_defaultZone:http://localhost:8761/eureka/}
    fetch-registry: ${eureka_client_fetch_registry:true}

management:
  endpoints:
    web:
      exposure:
        include: "*"