#server.port=9090
#spring.application.name=payment-service
#eureka.client.register-with-eureka=true
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

server:
  port: ${server_port:9091}
spring:
  application:
    name: ${APPLICATION_NAME:payment-service}
eureka.:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTRATION:true}
    service-url:
        defaultZone: ${eureka_client_serviceUrl_defaultZone:http://localhost:8761/eureka/}
    fetch-registry: ${eureka_client_fetch_registry:false}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


